-- ============================================
-- 杭州市小微园区评价数据分析平台 - H2数据库初始化脚本
-- ============================================

-- 1. 用户表
DROP TABLE IF EXISTS SYS_USER;
CREATE TABLE SYS_USER (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(50) NOT NULL UNIQUE,
    PASSWORD VARCHAR(200) NOT NULL,
    REAL_NAME VARCHAR(50),
    PHONE VARCHAR(20),
    ROLE VARCHAR(20),
    DISTRICT VARCHAR(50),
    DISTRICT_ID BIGINT,
    PARK_ID BIGINT,
    ROLE_TYPE TINYINT,
    STATUS TINYINT DEFAULT 1,
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 插入测试用户数据
INSERT INTO SYS_USER (USERNAME, PASSWORD, REAL_NAME, PHONE, ROLE, DISTRICT, ROLE_TYPE) VALUES
('admin', '$2a$10$N9qo8uLOickgx2ZMRZoMye.IjzqAKL9xL5jvMFVdNJHvGCgTq/VEq', '管理员', '13800138000', 'admin', '杭州市', 1),
('district01', '$2a$10$N9qo8uLOickgx2ZMRZoMye.IjzqAKL9xL5jvMFVdNJHvGCgTq/VEq', '西湖区管理员', '13800138001', 'district', '西湖区', 2),
('park01', '$2a$10$N9qo8uLOickgx2ZMRZoMye.IjzqAKL9xL5jvMFVdNJHvGCgTq/VEq', '紫金港园区管理员', '13800138002', 'park', '西湖区', 3);

-- 2. 区县信息表
DROP TABLE IF EXISTS DISTRICT_INFO;
CREATE TABLE DISTRICT_INFO (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    DISTRICT_CODE VARCHAR(20) NOT NULL UNIQUE,
    DISTRICT_NAME VARCHAR(100) NOT NULL UNIQUE,
    CITY VARCHAR(50) DEFAULT '杭州市',
    PROVINCE VARCHAR(50) DEFAULT '浙江省',
    SORT_ORDER INT DEFAULT 0,
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO DISTRICT_INFO (DISTRICT_CODE, DISTRICT_NAME, CITY, PROVINCE, SORT_ORDER) VALUES
('330102', '上城区', '杭州市', '浙江省', 1),
('330105', '拱墅区', '杭州市', '浙江省', 2),
('330106', '西湖区', '杭州市', '浙江省', 3),
('330108', '滨江区', '杭州市', '浙江省', 4),
('330109', '萧山区', '杭州市', '浙江省', 5),
('330110', '余杭区', '杭州市', '浙江省', 6),
('330111', '富阳区', '杭州市', '浙江省', 7),
('330112', '临安区', '杭州市', '浙江省', 8),
('330113', '临平区', '杭州市', '浙江省', 9),
('330114', '钱塘区', '杭州市', '浙江省', 10),
('330122', '桐庐县', '杭州市', '浙江省', 11),
('330127', '淳安县', '杭州市', '浙江省', 12),
('330182', '建德市', '杭州市', '浙江省', 13);

-- 3. 园区基础信息表
DROP TABLE IF EXISTS PARK_INFO;
CREATE TABLE PARK_INFO (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    PARK_CODE VARCHAR(50),
    PARK_NAME VARCHAR(200) NOT NULL,
    PARK_TYPE VARCHAR(50),
    DISTRICT_ID BIGINT,
    DISTRICT_NAME VARCHAR(50),
    ADDRESS VARCHAR(500),
    STAR_LEVEL INT DEFAULT 0,
    PERFORMANCE VARCHAR(20),
    PARK_STATUS VARCHAR(20),
    DEV_MODE VARCHAR(50),
    LAND_SOURCE VARCHAR(50),
    LAND_NATURE VARCHAR(50),
    RECOGNITION VARCHAR(100),
    IS_UPGRADE VARCHAR(10),
    UPGRADE_CONTENT TEXT,
    MAIN_INDUSTRY VARCHAR(500),
    INTRODUCTION TEXT,
    LAND_AREA DECIMAL(12,2),
    BUILD_AREA DECIMAL(12,2),
    RENT_REMAIN_AREA DECIMAL(12,2),
    SALE_REMAIN_AREA VARCHAR(50),
    RENTED_AREA DECIMAL(12,2),
    PUBLIC_FACILITIES TEXT,
    PUBLIC_SERVICES TEXT,
    OPERATION_ORG_NAME VARCHAR(200),
    OPERATION_ORG_CODE VARCHAR(50),
    OPERATION_ORG_NATURE VARCHAR(50),
    ORG_LEADER VARCHAR(50),
    ORG_LEADER_PHONE VARCHAR(20),
    ORG_CONTACT VARCHAR(50),
    ORG_CONTACT_PHONE VARCHAR(20),
    ENTERPRISE_COUNT INT DEFAULT 0,
    ABOVE_SCALE_COUNT INT DEFAULT 0,
    HIGH_TECH_COUNT INT DEFAULT 0,
    TECH_SME_COUNT INT DEFAULT 0,
    LISTED_COUNT INT DEFAULT 0,
    HIDDEN_CHAMPION_COUNT INT DEFAULT 0,
    NATIONAL_SRTI_COUNT INT DEFAULT 0,
    PROVINCIAL_SRTI_COUNT INT DEFAULT 0,
    INNOVATIVE_SME_COUNT INT DEFAULT 0,
    EMPLOYEE_COUNT INT DEFAULT 0,
    NATIONAL_TALENT INT DEFAULT 0,
    PROVINCIAL_TALENT INT DEFAULT 0,
    MASTER_ABOVE INT DEFAULT 0,
    SENIOR_ENGINEER INT DEFAULT 0,
    ENGINEER INT DEFAULT 0,
    SENIOR_TECHNICIAN INT DEFAULT 0,
    MASTER_DEGREE INT DEFAULT 0,
    PATENT_TOTAL INT DEFAULT 0,
    PATENT_INVENTION INT DEFAULT 0,
    PATENT_UTILITY INT DEFAULT 0,
    PATENT_DESIGN INT DEFAULT 0,
    CREATE_BY VARCHAR(50),
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(50),
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DELETED TINYINT DEFAULT 0
);

-- 4. 入驻企业表
DROP TABLE IF EXISTS ENTERPRISE_INFO;
CREATE TABLE ENTERPRISE_INFO (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    PARK_ID BIGINT,
    PARK_NAME VARCHAR(200),
    ENTERPRISE_NAME VARCHAR(200) NOT NULL,
    UNIFIED_SOCIAL_CREDIT_CODE VARCHAR(50),
    LEGAL_PERSON VARCHAR(50),
    REGISTERED_CAPITAL DECIMAL(18,2),
    ESTABLISH_DATE DATE,
    BUSINESS_SCOPE TEXT,
    ADDRESS VARCHAR(500),
    CONTACT_PHONE VARCHAR(20),
    EMPLOYEE_COUNT INT DEFAULT 0,
    ANNUAL_REVENUE DECIMAL(18,2),
    TAX_AMOUNT DECIMAL(18,2),
    INDUSTRY_TYPE VARCHAR(100),
    ENTER_TIME DATE,
    LEASE_AREA DECIMAL(12,2),
    STATUS VARCHAR(20) DEFAULT 'normal',
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DELETED TINYINT DEFAULT 0
);

-- 插入模拟企业数据
INSERT INTO ENTERPRISE_INFO (PARK_ID, PARK_NAME, ENTERPRISE_NAME, UNIFIED_SOCIAL_CREDIT_CODE, LEGAL_PERSON, REGISTERED_CAPITAL, INDUSTRY_TYPE) VALUES
(1, '紫金港生命健康产业园', '杭州生物科技有限公司', '91330106MA27W7YH9L', '张三', 500.00, '生物医药'),
(1, '紫金港生命健康产业园', '浙江医疗器械有限公司', '91330106MA27W7YK2R', '李四', 800.00, '医疗器械'),
(2, '杭州智慧信息产业园', '杭州软件技术有限公司', '91330108MA27W7YL5T', '王五', 300.00, '信息技术');

-- 5. 评价审核表
DROP TABLE IF EXISTS PARK_EVALUATION;
CREATE TABLE PARK_EVALUATION (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    PARK_ID BIGINT,
    PARK_NAME VARCHAR(200),
    DISTRICT_ID BIGINT,
    DISTRICT_NAME VARCHAR(50),
    PARK_TYPE VARCHAR(50),
    "YEAR" INT,
    STATUS TINYINT DEFAULT 0,
    DISTRICT_COMMENT TEXT,
    DISTRICT_AUDIT_TIME TIMESTAMP,
    CITY_COMMENT TEXT,
    CITY_AUDIT_TIME TIMESTAMP,
    SCORE DECIMAL(10,2),
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 插入模拟评价数据
INSERT INTO PARK_EVALUATION (PARK_ID, PARK_NAME, DISTRICT_ID, DISTRICT_NAME, PARK_TYPE, "YEAR", STATUS) VALUES
(1, '紫金港生命健康产业园', 3, '西湖区', '生产性制造类', 2024, 1),
(2, '杭州智慧信息产业园', 4, '滨江区', '生产性服务类', 2024, 2),
(3, '萧山智能制造产业园', 5, '萧山区', '生产性制造类', 2024, 3),
(4, '余杭数字创意产业园', 6, '余杭区', '生产性服务类', 2024, 1),
(5, '富阳新材料产业园', 7, '富阳区', '生产性制造类', 2024, 4);

-- 更新用户表的district_id
UPDATE SYS_USER SET DISTRICT_ID = (SELECT ID FROM DISTRICT_INFO WHERE DISTRICT_NAME = SYS_USER.DISTRICT) WHERE DISTRICT IS NOT NULL;

-- 插入模拟园区数据
INSERT INTO PARK_INFO (PARK_CODE, PARK_NAME, PARK_TYPE, DISTRICT_ID, DISTRICT_NAME, ADDRESS, PARK_STATUS, DEV_MODE, LAND_SOURCE, LAND_NATURE, RECOGNITION, IS_UPGRADE, MAIN_INDUSTRY, INTRODUCTION, LAND_AREA, BUILD_AREA, RENTED_AREA, RENT_REMAIN_AREA, SALE_REMAIN_AREA, OPERATION_ORG_NAME, OPERATION_ORG_NATURE, ORG_LEADER, ORG_LEADER_PHONE, ORG_CONTACT, ORG_CONTACT_PHONE, ENTERPRISE_COUNT, EMPLOYEE_COUNT) VALUES
('PK001', '紫金港生命健康产业园', '生产性制造类', 3, '西湖区', '西湖区三墩镇金蓬街368号', '已投运', '政府主导开发', '租用', '工业用地', '省级小微企业园', '是', '生物医药', '紫金港生命健康产业园位于杭州市西湖区，总占地面积40亩，建筑面积35043平方米。', 40, 35043, 25395.37, 3250, '-', '杭州紫金港科技城建设投资有限公司', '国有', '郑建', '15988115758', '沈烨琳', '15858172079', 15, 350),
('PK002', '杭州智慧信息产业园', '生产性服务类', 4, '滨江区', '滨江区江南大道100号', '已投运', '企业自主开发', '出让', '商业用地', '市级小微企业园', '否', '信息技术', '杭州智慧信息产业园坐落于滨江区核心区域，总建筑面积5万平方米。', 30, 50000, 42000.0, 8000, '0', '杭州智慧信息产业发展有限公司', '民营', '王建国', '13800138000', '李娜', '13900139000', 20, 500),
('PK003', '萧山智能制造产业园', '生产性制造类', 5, '萧山区', '萧山区经济技术开发区', '已投运', '政企合作', '出让', '工业用地', '国家级小微企业园', '是', '智能制造', '萧山智能制造产业园是萧山区重点打造的高端制造产业平台。', 100, 80000, 72000.0, 8000, '-', '萧山智能制造产业发展有限公司', '国有', '张伟', '13700137000', '陈静', '13600136000', 25, 800),
('PK004', '余杭数字创意产业园', '生产性服务类', 6, '余杭区', '余杭区梦想小镇', '已投运', '政府主导开发', '划拨', '商业用地', '省级小微企业园', '否', '数字创意', '余杭数字创意产业园位于梦想小镇核心区，总建筑面积3.5万平方米。', 25, 35000, 30000.0, 5000, '0', '杭州梦想小镇投资发展有限公司', '国有', '刘洋', '13500135000', '赵雪', '13400134000', 30, 450),
('PK005', '富阳新材料产业园', '生产性制造类', 7, '富阳区', '富阳区银湖街道', '在建', '企业自主开发', '出让', '工业用地', '-', '否', '新材料', '富阳新材料产业园是富阳区重点培育的新兴产业园区。', 120, 0, 0.0, 100000, '0', '富阳新材料产业投资有限公司', '民营', '陈明', '13300133000', '周芳', '13200132000', 0, 0),
('PK006', '临安科创孵化园', '生产性服务类', 8, '临安区', '临安区锦南新城', '已投运', '政府主导开发', '划拨', '科研用地', '市级小微企业园', '是', '科技孵化', '临安科创孵化园是临安区科技创新的重要载体，建筑面积2万平方米。', 15, 20000, 18000.0, 2000, '0', '临安科技创新服务中心', '国有', '吴强', '13100131000', '郑梅', '13000130000', 18, 280);
