UPDATE enterprise_info SET address = 'No. 101, Science Park Road, Xihu District, Hangzhou', industry = 'Cloud Computing', employee_count = 150, annual_output = 6000.00, annual_tax = 420.00 WHERE id = 1;
UPDATE enterprise_info SET address = 'No. 102, Science Park Road, Xihu District, Hangzhou', industry = 'Environmental Protection', employee_count = 80, annual_output = 2500.00, annual_tax = 175.00 WHERE id = 2;
UPDATE enterprise_info SET address = 'No. 103, Science Park Road, Xihu District, Hangzhou', industry = 'Semiconductor', employee_count = 200, annual_output = 8000.00, annual_tax = 560.00 WHERE id = 3;
UPDATE enterprise_info SET address = 'No. 104, Science Park Road, Xihu District, Hangzhou', industry = 'Biomedical', employee_count = 120, annual_output = 4000.00, annual_tax = 280.00 WHERE id = 4;
UPDATE enterprise_info SET address = 'No. 105, Science Park Road, Xihu District, Hangzhou', industry = 'New Materials', employee_count = 90, annual_output = 3000.00, annual_tax = 210.00 WHERE id = 5;
UPDATE enterprise_info SET address = 'No. 201, Hi-Tech Zone, Binjiang District, Hangzhou', industry = 'Smart Manufacturing', employee_count = 180, annual_output = 7000.00, annual_tax = 490.00 WHERE id = 6;
UPDATE enterprise_info SET address = 'No. 202, Hi-Tech Zone, Binjiang District, Hangzhou', industry = 'AI Technology', employee_count = 220, annual_output = 9000.00, annual_tax = 630.00 WHERE id = 7;
UPDATE enterprise_info SET address = 'No. 203, Hi-Tech Zone, Binjiang District, Hangzhou', industry = 'Digital Services', employee_count = 70, annual_output = 2000.00, annual_tax = 140.00 WHERE id = 8;
UPDATE enterprise_info SET address = 'No. 204, Hi-Tech Zone, Binjiang District, Hangzhou', industry = 'Smart City', employee_count = 130, annual_output = 5000.00, annual_tax = 350.00 WHERE id = 9;
UPDATE enterprise_info SET address = 'No. 205, Hi-Tech Zone, Binjiang District, Hangzhou', industry = 'Eco-tech', employee_count = 60, annual_output = 1500.00, annual_tax = 105.00 WHERE id = 10;
UPDATE enterprise_info SET address = 'No. 301, Future Science City, Yuhang District, Hangzhou', industry = 'Future Technology', employee_count = 250, annual_output = 10000.00, annual_tax = 700.00 WHERE id = 11;
UPDATE enterprise_info SET address = 'No. 302, Future Science City, Yuhang District, Hangzhou', industry = 'Biotechnology', employee_count = 100, annual_output = 3500.00, annual_tax = 245.00 WHERE id = 12;
UPDATE enterprise_info SET address = 'No. 303, Future Science City, Yuhang District, Hangzhou', industry = 'E-commerce', employee_count = 300, annual_output = 12000.00, annual_tax = 840.00 WHERE id = 13;
UPDATE enterprise_info SET address = 'No. 304, Future Science City, Yuhang District, Hangzhou', industry = 'Fintech', employee_count = 140, annual_output = 5500.00, annual_tax = 385.00 WHERE id = 14;
UPDATE enterprise_info SET address = 'No. 401, Qianjiang New City, Shangcheng District, Hangzhou', industry = 'Environmental Tech', employee_count = 75, annual_output = 2800.00, annual_tax = 196.00 WHERE id = 15;
UPDATE enterprise_info SET address = 'No. 402, Qianjiang New City, Shangcheng District, Hangzhou', industry = 'Cloud Services', employee_count = 160, annual_output = 6500.00, annual_tax = 455.00 WHERE id = 16;
UPDATE enterprise_info SET address = 'No. 403, Qianjiang New City, Shangcheng District, Hangzhou', industry = 'Big Data', employee_count = 110, annual_output = 4500.00, annual_tax = 315.00 WHERE id = 17;
UPDATE enterprise_info SET address = 'No. 404, Qianjiang New City, Shangcheng District, Hangzhou', industry = 'AI Research', employee_count = 190, annual_output = 7500.00, annual_tax = 525.00 WHERE id = 18;
UPDATE enterprise_info SET address = 'No. 501, Linping District, Hangzhou', industry = 'IoT', employee_count = 85, annual_output = 3200.00, annual_tax = 224.00 WHERE id = 19;
UPDATE enterprise_info SET address = 'No. 502, Linping District, Hangzhou', industry = 'Software Development', employee_count = 95, annual_output = 3800.00, annual_tax = 266.00 WHERE id = 20;
UPDATE enterprise_info SET address = 'No. 503, Linping District, Hangzhou', industry = 'Digital Technology', employee_count = 125, annual_output = 5200.00, annual_tax = 364.00 WHERE id = 21;
UPDATE enterprise_info SET address = 'No. 601, Xiaoshan District, Hangzhou', industry = 'Internet Services', employee_count = 170, annual_output = 6800.00, annual_tax = 476.00 WHERE id = 22;
UPDATE enterprise_info SET address = 'No. 602, Xiaoshan District, Hangzhou', industry = 'Blockchain', employee_count = 65, annual_output = 1800.00, annual_tax = 126.00 WHERE id = 23;
